### ISSUE TITLE
[file] Path constructor

### ISSUE THREAD

**Issue by cristianoc72** [phootwork/phootwork#22]
`phootwork\file\Path::__constructor` method accepts also empty strings as pathname. Does it make sense? I can see two possible behaviors here:

1. Force non empty strings
2. Accept empty strings but implement also `setPathname` method to define the property after the instantiation.

**Comment by gossi** [comment]
I think the idea was to have a non-empty `Path`, because anyway most methods wouldn't make sense, if you start by `new Path()`. Second is, that `Path` is immutable, which is why `setPathname()` wouldn't make sense, as this would be equivalent to `new Path()`. 

Third is, it shouldn't error, when an empty string is being put into. That is, when doing `new Path($whateverIhaveHereReturnedFromSomewhereElseThatIsPotentiallyEmpty);` 😂 That were my design decisions. You would have been in the need to wrap it with `try ... catch`. Yet in this case, an empty string is a valid value. Just don't get into the way of the developer, I think was the idea.

Comments?

**Comment by cristianoc72** [comment]
Yes, I can understand your points. In this case, we leave everything as is.
